spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.61:3306/zhili_exam?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: daoben
    password: Da0ben2014
    maxPoolSize: 30
    minPoolSize: 5

jpa:
  database: mysql
  hibernate:
    ddl-auto: update
    use-new-id-generator-mappings: false
    enable-lazy-load-no-trans: true
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: true
  show-sql: true
  mvc:
    async:
      request-timeout: 200000

logging:
  file: /data/app.log
  level:
    org.hibernate.SQL: debug
    com.idaoben: debug
    com.idaoben.utils.dto_assembler.MappingClassGenerator: info
    ControllerMethodLoggingAspect: debug
    com.huayin.web.exam.mapper: debug

upload:
  root:
    dir: C:/data
  max:
    size: 50
  image:
    extension: jpg,jpeg,bmp,png
  file:
    extension: zip,rar,7z,doc,docx,xls,xlsx,ppt,pptx,pdf,txt,jpg,jpeg,bmp,png
  url:
    append:
      path: true

auth:
  auth-debug-enabled: true

url:
  base:
    path: http://127.0.0.1:8080